import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :svarm, SvarmWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL removed — NPM Plus or Caddy handles SSL termination.
# If you need app-level HTTPS redirect, uncomment and rebuild:
# config :svarm, SvarmWeb.Endpoint,
#   force_ssl: [
#     rewrite_on: [:x_forwarded_proto],
#     exclude: [paths: ["/health"], hosts: ["localhost", "127.0.0.1"]]
#   ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
